export const CATEGORY_ADD = 'CATEGORY_ADD';
export const CATEGORY_SELECT = 'CATEGORY_SELECT';
export const CATEGORY_EDIT = 'CATEGORY_EDIT';
export const CATEGORY_DELETE = 'CATEGORY_DELETE';
export const CATEGORY_EXPAND = 'CATEGORY_EXPAND';

export const TASK_ADD = 'TASK_ADD';
export const TASK_SELECT = 'TASK_SELECT';
export const TASK_EDIT = 'TASK_EDIT';

export const SEARCH_TASK_REQUEST = 'SEARCH_TASK_REQUEST';
export const SEARCH_TASK_SUCCESS = 'SEARCH_TASK_SUCCESS';
export const SEARCH_TASK_FAILURE = 'SEARCH_TASK_FAILURE';

export const EDIT_MODE_ON = 'EDIT_MODE_ON';
export const EDIT_MODE_OFF = 'EDIT_MODE_OFF';
